/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.mycompany.hadoop_study.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CampaignEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CampaignEvent\",\"namespace\":\"com.mycompany.hadoop_study.avro\",\"fields\":[{\"name\":\"SID\",\"type\":[\"string\",\"null\"]},{\"name\":\"BID\",\"type\":[\"string\",\"null\"]},{\"name\":\"IO\",\"type\":[\"string\",\"null\"]},{\"name\":\"DATE\",\"type\":[\"string\",\"null\"]},{\"name\":\"PROPERTY_BOOKING\",\"type\":[\"string\",\"null\"]},{\"name\":\"SITE\",\"type\":[\"string\",\"null\"],\"doc\":\"In fact it is SITE NAME\"},{\"name\":\"POSITION\",\"type\":[\"string\",\"null\"]},{\"name\":\"LINE\",\"type\":[\"string\",\"null\"],\"doc\":\"It has another name ad_grp_placement_id\"},{\"name\":\"DEVICE\",\"type\":[\"string\",\"null\"],\"doc\":\"In fact it is the device name.\"},{\"name\":\"OS\",\"type\":[\"string\",\"null\"],\"doc\":\"In fact it is the operating system name.\"},{\"name\":\"BROWSER\",\"type\":[\"string\",\"null\"],\"doc\":\"In fact it is the browser name.\"},{\"name\":\"CARRIER\",\"type\":[\"string\",\"null\"],\"doc\":\"In fact it is the carrier name.\"},{\"name\":\"CREATIVEID\",\"type\":[\"string\",\"null\"]},{\"name\":\"IMPRESSIONS\",\"type\":[\"long\",\"null\"]},{\"name\":\"CLICKS\",\"type\":[\"long\",\"null\"]},{\"name\":\"SITEID\",\"type\":[\"string\",\"null\"]},{\"name\":\"DEVICEID\",\"type\":[\"string\",\"null\"]},{\"name\":\"OSID\",\"type\":[\"string\",\"null\"]},{\"name\":\"BROWSERID\",\"type\":[\"string\",\"null\"]},{\"name\":\"CARRIERID\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence SID;
  @Deprecated public java.lang.CharSequence BID;
  @Deprecated public java.lang.CharSequence IO;
  @Deprecated public java.lang.CharSequence DATE;
  @Deprecated public java.lang.CharSequence PROPERTY_BOOKING;
  /** In fact it is SITE NAME */
  @Deprecated public java.lang.CharSequence SITE;
  @Deprecated public java.lang.CharSequence POSITION;
  /** It has another name ad_grp_placement_id */
  @Deprecated public java.lang.CharSequence LINE;
  /** In fact it is the device name. */
  @Deprecated public java.lang.CharSequence DEVICE;
  /** In fact it is the operating system name. */
  @Deprecated public java.lang.CharSequence OS;
  /** In fact it is the browser name. */
  @Deprecated public java.lang.CharSequence BROWSER;
  /** In fact it is the carrier name. */
  @Deprecated public java.lang.CharSequence CARRIER;
  @Deprecated public java.lang.CharSequence CREATIVEID;
  @Deprecated public java.lang.Long IMPRESSIONS;
  @Deprecated public java.lang.Long CLICKS;
  @Deprecated public java.lang.CharSequence SITEID;
  @Deprecated public java.lang.CharSequence DEVICEID;
  @Deprecated public java.lang.CharSequence OSID;
  @Deprecated public java.lang.CharSequence BROWSERID;
  @Deprecated public java.lang.CharSequence CARRIERID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CampaignEvent() {}

  /**
   * All-args constructor.
   */
  public CampaignEvent(java.lang.CharSequence SID, java.lang.CharSequence BID, java.lang.CharSequence IO, java.lang.CharSequence DATE, java.lang.CharSequence PROPERTY_BOOKING, java.lang.CharSequence SITE, java.lang.CharSequence POSITION, java.lang.CharSequence LINE, java.lang.CharSequence DEVICE, java.lang.CharSequence OS, java.lang.CharSequence BROWSER, java.lang.CharSequence CARRIER, java.lang.CharSequence CREATIVEID, java.lang.Long IMPRESSIONS, java.lang.Long CLICKS, java.lang.CharSequence SITEID, java.lang.CharSequence DEVICEID, java.lang.CharSequence OSID, java.lang.CharSequence BROWSERID, java.lang.CharSequence CARRIERID) {
    this.SID = SID;
    this.BID = BID;
    this.IO = IO;
    this.DATE = DATE;
    this.PROPERTY_BOOKING = PROPERTY_BOOKING;
    this.SITE = SITE;
    this.POSITION = POSITION;
    this.LINE = LINE;
    this.DEVICE = DEVICE;
    this.OS = OS;
    this.BROWSER = BROWSER;
    this.CARRIER = CARRIER;
    this.CREATIVEID = CREATIVEID;
    this.IMPRESSIONS = IMPRESSIONS;
    this.CLICKS = CLICKS;
    this.SITEID = SITEID;
    this.DEVICEID = DEVICEID;
    this.OSID = OSID;
    this.BROWSERID = BROWSERID;
    this.CARRIERID = CARRIERID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SID;
    case 1: return BID;
    case 2: return IO;
    case 3: return DATE;
    case 4: return PROPERTY_BOOKING;
    case 5: return SITE;
    case 6: return POSITION;
    case 7: return LINE;
    case 8: return DEVICE;
    case 9: return OS;
    case 10: return BROWSER;
    case 11: return CARRIER;
    case 12: return CREATIVEID;
    case 13: return IMPRESSIONS;
    case 14: return CLICKS;
    case 15: return SITEID;
    case 16: return DEVICEID;
    case 17: return OSID;
    case 18: return BROWSERID;
    case 19: return CARRIERID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SID = (java.lang.CharSequence)value$; break;
    case 1: BID = (java.lang.CharSequence)value$; break;
    case 2: IO = (java.lang.CharSequence)value$; break;
    case 3: DATE = (java.lang.CharSequence)value$; break;
    case 4: PROPERTY_BOOKING = (java.lang.CharSequence)value$; break;
    case 5: SITE = (java.lang.CharSequence)value$; break;
    case 6: POSITION = (java.lang.CharSequence)value$; break;
    case 7: LINE = (java.lang.CharSequence)value$; break;
    case 8: DEVICE = (java.lang.CharSequence)value$; break;
    case 9: OS = (java.lang.CharSequence)value$; break;
    case 10: BROWSER = (java.lang.CharSequence)value$; break;
    case 11: CARRIER = (java.lang.CharSequence)value$; break;
    case 12: CREATIVEID = (java.lang.CharSequence)value$; break;
    case 13: IMPRESSIONS = (java.lang.Long)value$; break;
    case 14: CLICKS = (java.lang.Long)value$; break;
    case 15: SITEID = (java.lang.CharSequence)value$; break;
    case 16: DEVICEID = (java.lang.CharSequence)value$; break;
    case 17: OSID = (java.lang.CharSequence)value$; break;
    case 18: BROWSERID = (java.lang.CharSequence)value$; break;
    case 19: CARRIERID = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'SID' field.
   */
  public java.lang.CharSequence getSID() {
    return SID;
  }

  /**
   * Sets the value of the 'SID' field.
   * @param value the value to set.
   */
  public void setSID(java.lang.CharSequence value) {
    this.SID = value;
  }

  /**
   * Gets the value of the 'BID' field.
   */
  public java.lang.CharSequence getBID() {
    return BID;
  }

  /**
   * Sets the value of the 'BID' field.
   * @param value the value to set.
   */
  public void setBID(java.lang.CharSequence value) {
    this.BID = value;
  }

  /**
   * Gets the value of the 'IO' field.
   */
  public java.lang.CharSequence getIO() {
    return IO;
  }

  /**
   * Sets the value of the 'IO' field.
   * @param value the value to set.
   */
  public void setIO(java.lang.CharSequence value) {
    this.IO = value;
  }

  /**
   * Gets the value of the 'DATE' field.
   */
  public java.lang.CharSequence getDATE() {
    return DATE;
  }

  /**
   * Sets the value of the 'DATE' field.
   * @param value the value to set.
   */
  public void setDATE(java.lang.CharSequence value) {
    this.DATE = value;
  }

  /**
   * Gets the value of the 'PROPERTY_BOOKING' field.
   */
  public java.lang.CharSequence getPROPERTYBOOKING() {
    return PROPERTY_BOOKING;
  }

  /**
   * Sets the value of the 'PROPERTY_BOOKING' field.
   * @param value the value to set.
   */
  public void setPROPERTYBOOKING(java.lang.CharSequence value) {
    this.PROPERTY_BOOKING = value;
  }

  /**
   * Gets the value of the 'SITE' field.
   * In fact it is SITE NAME   */
  public java.lang.CharSequence getSITE() {
    return SITE;
  }

  /**
   * Sets the value of the 'SITE' field.
   * In fact it is SITE NAME   * @param value the value to set.
   */
  public void setSITE(java.lang.CharSequence value) {
    this.SITE = value;
  }

  /**
   * Gets the value of the 'POSITION' field.
   */
  public java.lang.CharSequence getPOSITION() {
    return POSITION;
  }

  /**
   * Sets the value of the 'POSITION' field.
   * @param value the value to set.
   */
  public void setPOSITION(java.lang.CharSequence value) {
    this.POSITION = value;
  }

  /**
   * Gets the value of the 'LINE' field.
   * It has another name ad_grp_placement_id   */
  public java.lang.CharSequence getLINE() {
    return LINE;
  }

  /**
   * Sets the value of the 'LINE' field.
   * It has another name ad_grp_placement_id   * @param value the value to set.
   */
  public void setLINE(java.lang.CharSequence value) {
    this.LINE = value;
  }

  /**
   * Gets the value of the 'DEVICE' field.
   * In fact it is the device name.   */
  public java.lang.CharSequence getDEVICE() {
    return DEVICE;
  }

  /**
   * Sets the value of the 'DEVICE' field.
   * In fact it is the device name.   * @param value the value to set.
   */
  public void setDEVICE(java.lang.CharSequence value) {
    this.DEVICE = value;
  }

  /**
   * Gets the value of the 'OS' field.
   * In fact it is the operating system name.   */
  public java.lang.CharSequence getOS() {
    return OS;
  }

  /**
   * Sets the value of the 'OS' field.
   * In fact it is the operating system name.   * @param value the value to set.
   */
  public void setOS(java.lang.CharSequence value) {
    this.OS = value;
  }

  /**
   * Gets the value of the 'BROWSER' field.
   * In fact it is the browser name.   */
  public java.lang.CharSequence getBROWSER() {
    return BROWSER;
  }

  /**
   * Sets the value of the 'BROWSER' field.
   * In fact it is the browser name.   * @param value the value to set.
   */
  public void setBROWSER(java.lang.CharSequence value) {
    this.BROWSER = value;
  }

  /**
   * Gets the value of the 'CARRIER' field.
   * In fact it is the carrier name.   */
  public java.lang.CharSequence getCARRIER() {
    return CARRIER;
  }

  /**
   * Sets the value of the 'CARRIER' field.
   * In fact it is the carrier name.   * @param value the value to set.
   */
  public void setCARRIER(java.lang.CharSequence value) {
    this.CARRIER = value;
  }

  /**
   * Gets the value of the 'CREATIVEID' field.
   */
  public java.lang.CharSequence getCREATIVEID() {
    return CREATIVEID;
  }

  /**
   * Sets the value of the 'CREATIVEID' field.
   * @param value the value to set.
   */
  public void setCREATIVEID(java.lang.CharSequence value) {
    this.CREATIVEID = value;
  }

  /**
   * Gets the value of the 'IMPRESSIONS' field.
   */
  public java.lang.Long getIMPRESSIONS() {
    return IMPRESSIONS;
  }

  /**
   * Sets the value of the 'IMPRESSIONS' field.
   * @param value the value to set.
   */
  public void setIMPRESSIONS(java.lang.Long value) {
    this.IMPRESSIONS = value;
  }

  /**
   * Gets the value of the 'CLICKS' field.
   */
  public java.lang.Long getCLICKS() {
    return CLICKS;
  }

  /**
   * Sets the value of the 'CLICKS' field.
   * @param value the value to set.
   */
  public void setCLICKS(java.lang.Long value) {
    this.CLICKS = value;
  }

  /**
   * Gets the value of the 'SITEID' field.
   */
  public java.lang.CharSequence getSITEID() {
    return SITEID;
  }

  /**
   * Sets the value of the 'SITEID' field.
   * @param value the value to set.
   */
  public void setSITEID(java.lang.CharSequence value) {
    this.SITEID = value;
  }

  /**
   * Gets the value of the 'DEVICEID' field.
   */
  public java.lang.CharSequence getDEVICEID() {
    return DEVICEID;
  }

  /**
   * Sets the value of the 'DEVICEID' field.
   * @param value the value to set.
   */
  public void setDEVICEID(java.lang.CharSequence value) {
    this.DEVICEID = value;
  }

  /**
   * Gets the value of the 'OSID' field.
   */
  public java.lang.CharSequence getOSID() {
    return OSID;
  }

  /**
   * Sets the value of the 'OSID' field.
   * @param value the value to set.
   */
  public void setOSID(java.lang.CharSequence value) {
    this.OSID = value;
  }

  /**
   * Gets the value of the 'BROWSERID' field.
   */
  public java.lang.CharSequence getBROWSERID() {
    return BROWSERID;
  }

  /**
   * Sets the value of the 'BROWSERID' field.
   * @param value the value to set.
   */
  public void setBROWSERID(java.lang.CharSequence value) {
    this.BROWSERID = value;
  }

  /**
   * Gets the value of the 'CARRIERID' field.
   */
  public java.lang.CharSequence getCARRIERID() {
    return CARRIERID;
  }

  /**
   * Sets the value of the 'CARRIERID' field.
   * @param value the value to set.
   */
  public void setCARRIERID(java.lang.CharSequence value) {
    this.CARRIERID = value;
  }

  /** Creates a new CampaignEvent RecordBuilder */
  public static com.mycompany.hadoop_study.avro.CampaignEvent.Builder newBuilder() {
    return new com.mycompany.hadoop_study.avro.CampaignEvent.Builder();
  }
  
  /** Creates a new CampaignEvent RecordBuilder by copying an existing Builder */
  public static com.mycompany.hadoop_study.avro.CampaignEvent.Builder newBuilder(com.mycompany.hadoop_study.avro.CampaignEvent.Builder other) {
    return new com.mycompany.hadoop_study.avro.CampaignEvent.Builder(other);
  }
  
  /** Creates a new CampaignEvent RecordBuilder by copying an existing CampaignEvent instance */
  public static com.mycompany.hadoop_study.avro.CampaignEvent.Builder newBuilder(com.mycompany.hadoop_study.avro.CampaignEvent other) {
    return new com.mycompany.hadoop_study.avro.CampaignEvent.Builder(other);
  }
  
  /**
   * RecordBuilder for CampaignEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CampaignEvent>
    implements org.apache.avro.data.RecordBuilder<CampaignEvent> {

    private java.lang.CharSequence SID;
    private java.lang.CharSequence BID;
    private java.lang.CharSequence IO;
    private java.lang.CharSequence DATE;
    private java.lang.CharSequence PROPERTY_BOOKING;
    private java.lang.CharSequence SITE;
    private java.lang.CharSequence POSITION;
    private java.lang.CharSequence LINE;
    private java.lang.CharSequence DEVICE;
    private java.lang.CharSequence OS;
    private java.lang.CharSequence BROWSER;
    private java.lang.CharSequence CARRIER;
    private java.lang.CharSequence CREATIVEID;
    private java.lang.Long IMPRESSIONS;
    private java.lang.Long CLICKS;
    private java.lang.CharSequence SITEID;
    private java.lang.CharSequence DEVICEID;
    private java.lang.CharSequence OSID;
    private java.lang.CharSequence BROWSERID;
    private java.lang.CharSequence CARRIERID;

    /** Creates a new Builder */
    private Builder() {
      super(com.mycompany.hadoop_study.avro.CampaignEvent.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.mycompany.hadoop_study.avro.CampaignEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SID)) {
        this.SID = data().deepCopy(fields()[0].schema(), other.SID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BID)) {
        this.BID = data().deepCopy(fields()[1].schema(), other.BID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.IO)) {
        this.IO = data().deepCopy(fields()[2].schema(), other.IO);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DATE)) {
        this.DATE = data().deepCopy(fields()[3].schema(), other.DATE);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.PROPERTY_BOOKING)) {
        this.PROPERTY_BOOKING = data().deepCopy(fields()[4].schema(), other.PROPERTY_BOOKING);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SITE)) {
        this.SITE = data().deepCopy(fields()[5].schema(), other.SITE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.POSITION)) {
        this.POSITION = data().deepCopy(fields()[6].schema(), other.POSITION);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.LINE)) {
        this.LINE = data().deepCopy(fields()[7].schema(), other.LINE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.DEVICE)) {
        this.DEVICE = data().deepCopy(fields()[8].schema(), other.DEVICE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.OS)) {
        this.OS = data().deepCopy(fields()[9].schema(), other.OS);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.BROWSER)) {
        this.BROWSER = data().deepCopy(fields()[10].schema(), other.BROWSER);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CARRIER)) {
        this.CARRIER = data().deepCopy(fields()[11].schema(), other.CARRIER);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CREATIVEID)) {
        this.CREATIVEID = data().deepCopy(fields()[12].schema(), other.CREATIVEID);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.IMPRESSIONS)) {
        this.IMPRESSIONS = data().deepCopy(fields()[13].schema(), other.IMPRESSIONS);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CLICKS)) {
        this.CLICKS = data().deepCopy(fields()[14].schema(), other.CLICKS);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.SITEID)) {
        this.SITEID = data().deepCopy(fields()[15].schema(), other.SITEID);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.DEVICEID)) {
        this.DEVICEID = data().deepCopy(fields()[16].schema(), other.DEVICEID);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.OSID)) {
        this.OSID = data().deepCopy(fields()[17].schema(), other.OSID);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.BROWSERID)) {
        this.BROWSERID = data().deepCopy(fields()[18].schema(), other.BROWSERID);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.CARRIERID)) {
        this.CARRIERID = data().deepCopy(fields()[19].schema(), other.CARRIERID);
        fieldSetFlags()[19] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CampaignEvent instance */
    private Builder(com.mycompany.hadoop_study.avro.CampaignEvent other) {
            super(com.mycompany.hadoop_study.avro.CampaignEvent.SCHEMA$);
      if (isValidValue(fields()[0], other.SID)) {
        this.SID = data().deepCopy(fields()[0].schema(), other.SID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BID)) {
        this.BID = data().deepCopy(fields()[1].schema(), other.BID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.IO)) {
        this.IO = data().deepCopy(fields()[2].schema(), other.IO);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.DATE)) {
        this.DATE = data().deepCopy(fields()[3].schema(), other.DATE);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.PROPERTY_BOOKING)) {
        this.PROPERTY_BOOKING = data().deepCopy(fields()[4].schema(), other.PROPERTY_BOOKING);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.SITE)) {
        this.SITE = data().deepCopy(fields()[5].schema(), other.SITE);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.POSITION)) {
        this.POSITION = data().deepCopy(fields()[6].schema(), other.POSITION);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.LINE)) {
        this.LINE = data().deepCopy(fields()[7].schema(), other.LINE);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.DEVICE)) {
        this.DEVICE = data().deepCopy(fields()[8].schema(), other.DEVICE);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.OS)) {
        this.OS = data().deepCopy(fields()[9].schema(), other.OS);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.BROWSER)) {
        this.BROWSER = data().deepCopy(fields()[10].schema(), other.BROWSER);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.CARRIER)) {
        this.CARRIER = data().deepCopy(fields()[11].schema(), other.CARRIER);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.CREATIVEID)) {
        this.CREATIVEID = data().deepCopy(fields()[12].schema(), other.CREATIVEID);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.IMPRESSIONS)) {
        this.IMPRESSIONS = data().deepCopy(fields()[13].schema(), other.IMPRESSIONS);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.CLICKS)) {
        this.CLICKS = data().deepCopy(fields()[14].schema(), other.CLICKS);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.SITEID)) {
        this.SITEID = data().deepCopy(fields()[15].schema(), other.SITEID);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.DEVICEID)) {
        this.DEVICEID = data().deepCopy(fields()[16].schema(), other.DEVICEID);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.OSID)) {
        this.OSID = data().deepCopy(fields()[17].schema(), other.OSID);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.BROWSERID)) {
        this.BROWSERID = data().deepCopy(fields()[18].schema(), other.BROWSERID);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.CARRIERID)) {
        this.CARRIERID = data().deepCopy(fields()[19].schema(), other.CARRIERID);
        fieldSetFlags()[19] = true;
      }
    }

    /** Gets the value of the 'SID' field */
    public java.lang.CharSequence getSID() {
      return SID;
    }
    
    /** Sets the value of the 'SID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setSID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.SID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'SID' field has been set */
    public boolean hasSID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'SID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearSID() {
      SID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'BID' field */
    public java.lang.CharSequence getBID() {
      return BID;
    }
    
    /** Sets the value of the 'BID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setBID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.BID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'BID' field has been set */
    public boolean hasBID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'BID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearBID() {
      BID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'IO' field */
    public java.lang.CharSequence getIO() {
      return IO;
    }
    
    /** Sets the value of the 'IO' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setIO(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.IO = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'IO' field has been set */
    public boolean hasIO() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'IO' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearIO() {
      IO = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'DATE' field */
    public java.lang.CharSequence getDATE() {
      return DATE;
    }
    
    /** Sets the value of the 'DATE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setDATE(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.DATE = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'DATE' field has been set */
    public boolean hasDATE() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'DATE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearDATE() {
      DATE = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'PROPERTY_BOOKING' field */
    public java.lang.CharSequence getPROPERTYBOOKING() {
      return PROPERTY_BOOKING;
    }
    
    /** Sets the value of the 'PROPERTY_BOOKING' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setPROPERTYBOOKING(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.PROPERTY_BOOKING = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'PROPERTY_BOOKING' field has been set */
    public boolean hasPROPERTYBOOKING() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'PROPERTY_BOOKING' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearPROPERTYBOOKING() {
      PROPERTY_BOOKING = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'SITE' field */
    public java.lang.CharSequence getSITE() {
      return SITE;
    }
    
    /** Sets the value of the 'SITE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setSITE(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.SITE = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'SITE' field has been set */
    public boolean hasSITE() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'SITE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearSITE() {
      SITE = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'POSITION' field */
    public java.lang.CharSequence getPOSITION() {
      return POSITION;
    }
    
    /** Sets the value of the 'POSITION' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setPOSITION(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.POSITION = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'POSITION' field has been set */
    public boolean hasPOSITION() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'POSITION' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearPOSITION() {
      POSITION = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'LINE' field */
    public java.lang.CharSequence getLINE() {
      return LINE;
    }
    
    /** Sets the value of the 'LINE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setLINE(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.LINE = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'LINE' field has been set */
    public boolean hasLINE() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'LINE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearLINE() {
      LINE = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'DEVICE' field */
    public java.lang.CharSequence getDEVICE() {
      return DEVICE;
    }
    
    /** Sets the value of the 'DEVICE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setDEVICE(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.DEVICE = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'DEVICE' field has been set */
    public boolean hasDEVICE() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'DEVICE' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearDEVICE() {
      DEVICE = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'OS' field */
    public java.lang.CharSequence getOS() {
      return OS;
    }
    
    /** Sets the value of the 'OS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setOS(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.OS = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'OS' field has been set */
    public boolean hasOS() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'OS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearOS() {
      OS = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'BROWSER' field */
    public java.lang.CharSequence getBROWSER() {
      return BROWSER;
    }
    
    /** Sets the value of the 'BROWSER' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setBROWSER(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.BROWSER = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'BROWSER' field has been set */
    public boolean hasBROWSER() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'BROWSER' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearBROWSER() {
      BROWSER = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'CARRIER' field */
    public java.lang.CharSequence getCARRIER() {
      return CARRIER;
    }
    
    /** Sets the value of the 'CARRIER' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setCARRIER(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.CARRIER = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'CARRIER' field has been set */
    public boolean hasCARRIER() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'CARRIER' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearCARRIER() {
      CARRIER = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'CREATIVEID' field */
    public java.lang.CharSequence getCREATIVEID() {
      return CREATIVEID;
    }
    
    /** Sets the value of the 'CREATIVEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setCREATIVEID(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.CREATIVEID = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'CREATIVEID' field has been set */
    public boolean hasCREATIVEID() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'CREATIVEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearCREATIVEID() {
      CREATIVEID = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'IMPRESSIONS' field */
    public java.lang.Long getIMPRESSIONS() {
      return IMPRESSIONS;
    }
    
    /** Sets the value of the 'IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setIMPRESSIONS(java.lang.Long value) {
      validate(fields()[13], value);
      this.IMPRESSIONS = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'IMPRESSIONS' field has been set */
    public boolean hasIMPRESSIONS() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearIMPRESSIONS() {
      IMPRESSIONS = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'CLICKS' field */
    public java.lang.Long getCLICKS() {
      return CLICKS;
    }
    
    /** Sets the value of the 'CLICKS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setCLICKS(java.lang.Long value) {
      validate(fields()[14], value);
      this.CLICKS = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'CLICKS' field has been set */
    public boolean hasCLICKS() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'CLICKS' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearCLICKS() {
      CLICKS = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'SITEID' field */
    public java.lang.CharSequence getSITEID() {
      return SITEID;
    }
    
    /** Sets the value of the 'SITEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setSITEID(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.SITEID = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'SITEID' field has been set */
    public boolean hasSITEID() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'SITEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearSITEID() {
      SITEID = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'DEVICEID' field */
    public java.lang.CharSequence getDEVICEID() {
      return DEVICEID;
    }
    
    /** Sets the value of the 'DEVICEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setDEVICEID(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.DEVICEID = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'DEVICEID' field has been set */
    public boolean hasDEVICEID() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'DEVICEID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearDEVICEID() {
      DEVICEID = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'OSID' field */
    public java.lang.CharSequence getOSID() {
      return OSID;
    }
    
    /** Sets the value of the 'OSID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setOSID(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.OSID = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'OSID' field has been set */
    public boolean hasOSID() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'OSID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearOSID() {
      OSID = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'BROWSERID' field */
    public java.lang.CharSequence getBROWSERID() {
      return BROWSERID;
    }
    
    /** Sets the value of the 'BROWSERID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setBROWSERID(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.BROWSERID = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'BROWSERID' field has been set */
    public boolean hasBROWSERID() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'BROWSERID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearBROWSERID() {
      BROWSERID = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'CARRIERID' field */
    public java.lang.CharSequence getCARRIERID() {
      return CARRIERID;
    }
    
    /** Sets the value of the 'CARRIERID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder setCARRIERID(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.CARRIERID = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'CARRIERID' field has been set */
    public boolean hasCARRIERID() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'CARRIERID' field */
    public com.mycompany.hadoop_study.avro.CampaignEvent.Builder clearCARRIERID() {
      CARRIERID = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    @Override
    public CampaignEvent build() {
      try {
        CampaignEvent record = new CampaignEvent();
        record.SID = fieldSetFlags()[0] ? this.SID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.BID = fieldSetFlags()[1] ? this.BID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.IO = fieldSetFlags()[2] ? this.IO : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.DATE = fieldSetFlags()[3] ? this.DATE : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.PROPERTY_BOOKING = fieldSetFlags()[4] ? this.PROPERTY_BOOKING : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.SITE = fieldSetFlags()[5] ? this.SITE : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.POSITION = fieldSetFlags()[6] ? this.POSITION : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.LINE = fieldSetFlags()[7] ? this.LINE : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.DEVICE = fieldSetFlags()[8] ? this.DEVICE : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.OS = fieldSetFlags()[9] ? this.OS : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.BROWSER = fieldSetFlags()[10] ? this.BROWSER : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.CARRIER = fieldSetFlags()[11] ? this.CARRIER : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.CREATIVEID = fieldSetFlags()[12] ? this.CREATIVEID : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.IMPRESSIONS = fieldSetFlags()[13] ? this.IMPRESSIONS : (java.lang.Long) defaultValue(fields()[13]);
        record.CLICKS = fieldSetFlags()[14] ? this.CLICKS : (java.lang.Long) defaultValue(fields()[14]);
        record.SITEID = fieldSetFlags()[15] ? this.SITEID : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.DEVICEID = fieldSetFlags()[16] ? this.DEVICEID : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.OSID = fieldSetFlags()[17] ? this.OSID : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.BROWSERID = fieldSetFlags()[18] ? this.BROWSERID : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.CARRIERID = fieldSetFlags()[19] ? this.CARRIERID : (java.lang.CharSequence) defaultValue(fields()[19]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
