/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.mycompany.hadoop_study.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserEngagement extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserEngagement\",\"namespace\":\"com.mycompany.hadoop_study.avro\",\"fields\":[{\"name\":\"SID\",\"type\":[\"string\",\"null\"]},{\"name\":\"BID\",\"type\":[\"string\",\"null\"]},{\"name\":\"DATE\",\"type\":[\"string\",\"null\"]},{\"name\":\"NETWORK_IMPRESSIONS\",\"type\":[\"long\",\"null\"]},{\"name\":\"NETWORK_ADCLICKS\",\"type\":[\"long\",\"null\"]},{\"name\":\"MOBILE_NETWORK_IMPRESSIONS\",\"type\":[\"long\",\"null\"]},{\"name\":\"MOBILE_NETWORK_ADCLICKS\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence SID;
  @Deprecated public java.lang.CharSequence BID;
  @Deprecated public java.lang.CharSequence DATE;
  @Deprecated public java.lang.Long NETWORK_IMPRESSIONS;
  @Deprecated public java.lang.Long NETWORK_ADCLICKS;
  @Deprecated public java.lang.Long MOBILE_NETWORK_IMPRESSIONS;
  @Deprecated public java.lang.Long MOBILE_NETWORK_ADCLICKS;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public UserEngagement() {}

  /**
   * All-args constructor.
   */
  public UserEngagement(java.lang.CharSequence SID, java.lang.CharSequence BID, java.lang.CharSequence DATE, java.lang.Long NETWORK_IMPRESSIONS, java.lang.Long NETWORK_ADCLICKS, java.lang.Long MOBILE_NETWORK_IMPRESSIONS, java.lang.Long MOBILE_NETWORK_ADCLICKS) {
    this.SID = SID;
    this.BID = BID;
    this.DATE = DATE;
    this.NETWORK_IMPRESSIONS = NETWORK_IMPRESSIONS;
    this.NETWORK_ADCLICKS = NETWORK_ADCLICKS;
    this.MOBILE_NETWORK_IMPRESSIONS = MOBILE_NETWORK_IMPRESSIONS;
    this.MOBILE_NETWORK_ADCLICKS = MOBILE_NETWORK_ADCLICKS;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return SID;
    case 1: return BID;
    case 2: return DATE;
    case 3: return NETWORK_IMPRESSIONS;
    case 4: return NETWORK_ADCLICKS;
    case 5: return MOBILE_NETWORK_IMPRESSIONS;
    case 6: return MOBILE_NETWORK_ADCLICKS;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: SID = (java.lang.CharSequence)value$; break;
    case 1: BID = (java.lang.CharSequence)value$; break;
    case 2: DATE = (java.lang.CharSequence)value$; break;
    case 3: NETWORK_IMPRESSIONS = (java.lang.Long)value$; break;
    case 4: NETWORK_ADCLICKS = (java.lang.Long)value$; break;
    case 5: MOBILE_NETWORK_IMPRESSIONS = (java.lang.Long)value$; break;
    case 6: MOBILE_NETWORK_ADCLICKS = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'SID' field.
   */
  public java.lang.CharSequence getSID() {
    return SID;
  }

  /**
   * Sets the value of the 'SID' field.
   * @param value the value to set.
   */
  public void setSID(java.lang.CharSequence value) {
    this.SID = value;
  }

  /**
   * Gets the value of the 'BID' field.
   */
  public java.lang.CharSequence getBID() {
    return BID;
  }

  /**
   * Sets the value of the 'BID' field.
   * @param value the value to set.
   */
  public void setBID(java.lang.CharSequence value) {
    this.BID = value;
  }

  /**
   * Gets the value of the 'DATE' field.
   */
  public java.lang.CharSequence getDATE() {
    return DATE;
  }

  /**
   * Sets the value of the 'DATE' field.
   * @param value the value to set.
   */
  public void setDATE(java.lang.CharSequence value) {
    this.DATE = value;
  }

  /**
   * Gets the value of the 'NETWORK_IMPRESSIONS' field.
   */
  public java.lang.Long getNETWORKIMPRESSIONS() {
    return NETWORK_IMPRESSIONS;
  }

  /**
   * Sets the value of the 'NETWORK_IMPRESSIONS' field.
   * @param value the value to set.
   */
  public void setNETWORKIMPRESSIONS(java.lang.Long value) {
    this.NETWORK_IMPRESSIONS = value;
  }

  /**
   * Gets the value of the 'NETWORK_ADCLICKS' field.
   */
  public java.lang.Long getNETWORKADCLICKS() {
    return NETWORK_ADCLICKS;
  }

  /**
   * Sets the value of the 'NETWORK_ADCLICKS' field.
   * @param value the value to set.
   */
  public void setNETWORKADCLICKS(java.lang.Long value) {
    this.NETWORK_ADCLICKS = value;
  }

  /**
   * Gets the value of the 'MOBILE_NETWORK_IMPRESSIONS' field.
   */
  public java.lang.Long getMOBILENETWORKIMPRESSIONS() {
    return MOBILE_NETWORK_IMPRESSIONS;
  }

  /**
   * Sets the value of the 'MOBILE_NETWORK_IMPRESSIONS' field.
   * @param value the value to set.
   */
  public void setMOBILENETWORKIMPRESSIONS(java.lang.Long value) {
    this.MOBILE_NETWORK_IMPRESSIONS = value;
  }

  /**
   * Gets the value of the 'MOBILE_NETWORK_ADCLICKS' field.
   */
  public java.lang.Long getMOBILENETWORKADCLICKS() {
    return MOBILE_NETWORK_ADCLICKS;
  }

  /**
   * Sets the value of the 'MOBILE_NETWORK_ADCLICKS' field.
   * @param value the value to set.
   */
  public void setMOBILENETWORKADCLICKS(java.lang.Long value) {
    this.MOBILE_NETWORK_ADCLICKS = value;
  }

  /** Creates a new UserEngagement RecordBuilder */
  public static com.mycompany.hadoop_study.avro.UserEngagement.Builder newBuilder() {
    return new com.mycompany.hadoop_study.avro.UserEngagement.Builder();
  }
  
  /** Creates a new UserEngagement RecordBuilder by copying an existing Builder */
  public static com.mycompany.hadoop_study.avro.UserEngagement.Builder newBuilder(com.mycompany.hadoop_study.avro.UserEngagement.Builder other) {
    return new com.mycompany.hadoop_study.avro.UserEngagement.Builder(other);
  }
  
  /** Creates a new UserEngagement RecordBuilder by copying an existing UserEngagement instance */
  public static com.mycompany.hadoop_study.avro.UserEngagement.Builder newBuilder(com.mycompany.hadoop_study.avro.UserEngagement other) {
    return new com.mycompany.hadoop_study.avro.UserEngagement.Builder(other);
  }
  
  /**
   * RecordBuilder for UserEngagement instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserEngagement>
    implements org.apache.avro.data.RecordBuilder<UserEngagement> {

    private java.lang.CharSequence SID;
    private java.lang.CharSequence BID;
    private java.lang.CharSequence DATE;
    private java.lang.Long NETWORK_IMPRESSIONS;
    private java.lang.Long NETWORK_ADCLICKS;
    private java.lang.Long MOBILE_NETWORK_IMPRESSIONS;
    private java.lang.Long MOBILE_NETWORK_ADCLICKS;

    /** Creates a new Builder */
    private Builder() {
      super(com.mycompany.hadoop_study.avro.UserEngagement.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.mycompany.hadoop_study.avro.UserEngagement.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.SID)) {
        this.SID = data().deepCopy(fields()[0].schema(), other.SID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BID)) {
        this.BID = data().deepCopy(fields()[1].schema(), other.BID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DATE)) {
        this.DATE = data().deepCopy(fields()[2].schema(), other.DATE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.NETWORK_IMPRESSIONS)) {
        this.NETWORK_IMPRESSIONS = data().deepCopy(fields()[3].schema(), other.NETWORK_IMPRESSIONS);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.NETWORK_ADCLICKS)) {
        this.NETWORK_ADCLICKS = data().deepCopy(fields()[4].schema(), other.NETWORK_ADCLICKS);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.MOBILE_NETWORK_IMPRESSIONS)) {
        this.MOBILE_NETWORK_IMPRESSIONS = data().deepCopy(fields()[5].schema(), other.MOBILE_NETWORK_IMPRESSIONS);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.MOBILE_NETWORK_ADCLICKS)) {
        this.MOBILE_NETWORK_ADCLICKS = data().deepCopy(fields()[6].schema(), other.MOBILE_NETWORK_ADCLICKS);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UserEngagement instance */
    private Builder(com.mycompany.hadoop_study.avro.UserEngagement other) {
            super(com.mycompany.hadoop_study.avro.UserEngagement.SCHEMA$);
      if (isValidValue(fields()[0], other.SID)) {
        this.SID = data().deepCopy(fields()[0].schema(), other.SID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.BID)) {
        this.BID = data().deepCopy(fields()[1].schema(), other.BID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.DATE)) {
        this.DATE = data().deepCopy(fields()[2].schema(), other.DATE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.NETWORK_IMPRESSIONS)) {
        this.NETWORK_IMPRESSIONS = data().deepCopy(fields()[3].schema(), other.NETWORK_IMPRESSIONS);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.NETWORK_ADCLICKS)) {
        this.NETWORK_ADCLICKS = data().deepCopy(fields()[4].schema(), other.NETWORK_ADCLICKS);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.MOBILE_NETWORK_IMPRESSIONS)) {
        this.MOBILE_NETWORK_IMPRESSIONS = data().deepCopy(fields()[5].schema(), other.MOBILE_NETWORK_IMPRESSIONS);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.MOBILE_NETWORK_ADCLICKS)) {
        this.MOBILE_NETWORK_ADCLICKS = data().deepCopy(fields()[6].schema(), other.MOBILE_NETWORK_ADCLICKS);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'SID' field */
    public java.lang.CharSequence getSID() {
      return SID;
    }
    
    /** Sets the value of the 'SID' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setSID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.SID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'SID' field has been set */
    public boolean hasSID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'SID' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearSID() {
      SID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'BID' field */
    public java.lang.CharSequence getBID() {
      return BID;
    }
    
    /** Sets the value of the 'BID' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setBID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.BID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'BID' field has been set */
    public boolean hasBID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'BID' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearBID() {
      BID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'DATE' field */
    public java.lang.CharSequence getDATE() {
      return DATE;
    }
    
    /** Sets the value of the 'DATE' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setDATE(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.DATE = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'DATE' field has been set */
    public boolean hasDATE() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'DATE' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearDATE() {
      DATE = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'NETWORK_IMPRESSIONS' field */
    public java.lang.Long getNETWORKIMPRESSIONS() {
      return NETWORK_IMPRESSIONS;
    }
    
    /** Sets the value of the 'NETWORK_IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setNETWORKIMPRESSIONS(java.lang.Long value) {
      validate(fields()[3], value);
      this.NETWORK_IMPRESSIONS = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'NETWORK_IMPRESSIONS' field has been set */
    public boolean hasNETWORKIMPRESSIONS() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'NETWORK_IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearNETWORKIMPRESSIONS() {
      NETWORK_IMPRESSIONS = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'NETWORK_ADCLICKS' field */
    public java.lang.Long getNETWORKADCLICKS() {
      return NETWORK_ADCLICKS;
    }
    
    /** Sets the value of the 'NETWORK_ADCLICKS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setNETWORKADCLICKS(java.lang.Long value) {
      validate(fields()[4], value);
      this.NETWORK_ADCLICKS = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'NETWORK_ADCLICKS' field has been set */
    public boolean hasNETWORKADCLICKS() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'NETWORK_ADCLICKS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearNETWORKADCLICKS() {
      NETWORK_ADCLICKS = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'MOBILE_NETWORK_IMPRESSIONS' field */
    public java.lang.Long getMOBILENETWORKIMPRESSIONS() {
      return MOBILE_NETWORK_IMPRESSIONS;
    }
    
    /** Sets the value of the 'MOBILE_NETWORK_IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setMOBILENETWORKIMPRESSIONS(java.lang.Long value) {
      validate(fields()[5], value);
      this.MOBILE_NETWORK_IMPRESSIONS = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'MOBILE_NETWORK_IMPRESSIONS' field has been set */
    public boolean hasMOBILENETWORKIMPRESSIONS() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'MOBILE_NETWORK_IMPRESSIONS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearMOBILENETWORKIMPRESSIONS() {
      MOBILE_NETWORK_IMPRESSIONS = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'MOBILE_NETWORK_ADCLICKS' field */
    public java.lang.Long getMOBILENETWORKADCLICKS() {
      return MOBILE_NETWORK_ADCLICKS;
    }
    
    /** Sets the value of the 'MOBILE_NETWORK_ADCLICKS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder setMOBILENETWORKADCLICKS(java.lang.Long value) {
      validate(fields()[6], value);
      this.MOBILE_NETWORK_ADCLICKS = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'MOBILE_NETWORK_ADCLICKS' field has been set */
    public boolean hasMOBILENETWORKADCLICKS() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'MOBILE_NETWORK_ADCLICKS' field */
    public com.mycompany.hadoop_study.avro.UserEngagement.Builder clearMOBILENETWORKADCLICKS() {
      MOBILE_NETWORK_ADCLICKS = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public UserEngagement build() {
      try {
        UserEngagement record = new UserEngagement();
        record.SID = fieldSetFlags()[0] ? this.SID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.BID = fieldSetFlags()[1] ? this.BID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.DATE = fieldSetFlags()[2] ? this.DATE : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.NETWORK_IMPRESSIONS = fieldSetFlags()[3] ? this.NETWORK_IMPRESSIONS : (java.lang.Long) defaultValue(fields()[3]);
        record.NETWORK_ADCLICKS = fieldSetFlags()[4] ? this.NETWORK_ADCLICKS : (java.lang.Long) defaultValue(fields()[4]);
        record.MOBILE_NETWORK_IMPRESSIONS = fieldSetFlags()[5] ? this.MOBILE_NETWORK_IMPRESSIONS : (java.lang.Long) defaultValue(fields()[5]);
        record.MOBILE_NETWORK_ADCLICKS = fieldSetFlags()[6] ? this.MOBILE_NETWORK_ADCLICKS : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
